name: sswavenet
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - intel-openmp=2018.0.0=hc7b2577_8
  - mkl=2018.0.1=h19d6760_4
  - mkl-service=1.1.2=py27hb2d42c5_4
  - ca-certificates=2018.1.18=0
  - certifi=2018.1.18=py27_0
  - h5py=2.7.1=py27_2
  - hdf5=1.10.1=2
  - keras=2.1.5=py27_0
  - libgpuarray=0.7.5=0
  - mako=1.0.7=py27_0
  - markupsafe=1.0=py27_0
  - openssl=1.0.2n=0
  - pygpu=0.7.5=py27_0
  - pyyaml=3.12=py27_1
  - six=1.11.0=py27_1
  - theano=1.0.1=py27_1
  - yaml=0.1.7=0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - ncurses=6.0=h9df7e31_2
  - numpy=1.14.2=py27hdbf6ddf_0
  - pip=9.0.1=py27_5
  - python=2.7.14=h1571d57_30
  - readline=7.0=ha6073c6_4
  - scipy=1.0.0=py27hf5f0f52_0
  - setuptools=38.5.1=py27_0
  - sqlite=3.22.0=h1bed415_0
  - tk=8.6.7=hc745277_3
  - wheel=0.30.0=py27h2bc6bb2_1
  - zlib=1.2.11=ha838bed_2
  - pip:
    - cffi==1.11.5
    - functools32==3.2.3.post2
    - jsonschema==2.6.0
    - musdb==0.2.3
    - museval==0.2.0
    - pyaml==17.12.1
    - pycparser==2.18
    - simplejson==3.13.2
    - soundfile==0.9.0
    - stempeg==0.1.3
    - tqdm==4.19.7
